---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - nodejs

- name: Download and install gactions
  get_url:
    url: "{{ gactions_download_url }}"
    dest: /usr/bin/
    mode: u+rwx,g+rx,o+x

- name: Create deploy_directory directory
  file: path={{ deploy_directory }} state=directory owner={{ deploy_user }} group={{ deploy_user }} mode=0775

- name: Clone google-action-tiger repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ deploy_directory }}"

- name: Copy config file
  copy:
    src: ../../../../config
    dest: "{{ deploy_directory }}/config"

- name: Copy credentials file
  copy:
    src: ../../../../creds.data
    dest: "{{ deploy_directory }}/creds.data"

- name: Set file permissions for deploy_user
  file:
    path: "{{ deploy_directory }}"
    state: directory
    recurse: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Setup daily cron job
  cron: name="Google Action Tiger Preview" user="{{ deploy_user }}" minute="{{ cron_minute }}" hour="{{ cron_hour }}"
    job="cd {{ deploy_directory }} && git pull && ./{{ deploy_command }}"
