---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - nodejs

- name: Create deploy_directory directory
  file: path={{ deploy_directory }} state=directory owner={{ deploy_user }} group={{ deploy_user }} mode=0775

- name: Clone google-action-tiger repository
  git:
    repo: https://github.com/bradyholt/google-action-tiger.git
    dest: "{{ deploy_directory }}"

- name: Download gactions
  get_url:
    url: https://dl.google.com/gactions/updates/bin/linux/amd64/gactions/gactions
    dest: "{{ deploy_directory }}/gactions"
    mode: u+rwx,g+rx,o+x

- name: Copy config file
  copy:
    src: ../../../../config
    dest: "{{ deploy_directory }}/config"

- name: Copy credentials file
  copy:
    src: ../../../../creds.data
    dest: "{{ deploy_directory }}/creds.data"

- name: Set file permissions for deploy_user
  file:
    path: "{{ deploy_directory }}"
    state: directory
    recurse: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Setup daily cron job
  cron: name="Google Action Tiger Preview" user="{{ deploy_user }}" minute="0" hour="2"
    job="/bin/bash -l -c 'cd {{ deploy_directory }} && git pull && ./deploy-google-assistant.sh'"